---
ansible_python_interpreter: /usr/bin/python3
test_dependencies:
  - gawk
  - make
  - git
  - ruby-dev
  - rubygems
  - man

build_tools:
  - autoconf
  - automake
  - build-essential
  - imagemagick
  - texinfo
  - transfig
